require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

module BetterTogether
  RSpec.describe "/resource_permissions", type: :request do
    include Engine.routes.url_helpers

    before(:all) do
      Rails.application.load_seed
    end
  
    # This should return the minimal set of attributes required to create a valid
    # BetterTogether::ResourcePermission. As you add validations to BetterTogether::ResourcePermission, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    describe "GET /index" do
      it "renders a successful response" do
        BetterTogether::ResourcePermission.create! valid_attributes
        get resource_permissions_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      it "renders a successful response" do
        resource_permission = BetterTogether::ResourcePermission.create! valid_attributes
        get resource_permission_url(resource_permission)
        expect(response).to be_successful
      end
    end

    describe "GET /new" do
      it "renders a successful response" do
        get new_resource_permission_url
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      it "renders a successful response" do
        resource_permission = BetterTogether::ResourcePermission.create! valid_attributes
        get edit_resource_permission_url(resource_permission)
        expect(response).to be_successful
      end
    end

    describe "POST /create" do
      context "with valid parameters" do
        it "creates a new BetterTogether::ResourcePermission" do
          expect {
            post resource_permissions_url, params: { resource_permission: valid_attributes }
          }.to change(BetterTogether::ResourcePermission, :count).by(1)
        end

        it "redirects to the created resource_permission" do
          post resource_permissions_url, params: { resource_permission: valid_attributes }
          expect(response).to redirect_to(resource_permission_url(BetterTogether::ResourcePermission.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new BetterTogether::ResourcePermission" do
          expect {
            post resource_permissions_url, params: { resource_permission: invalid_attributes }
          }.to change(BetterTogether::ResourcePermission, :count).by(0)
        end

    
        it "renders a response with 422 status (i.e. to display the 'new' template)" do
          post resource_permissions_url, params: { resource_permission: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_entity)
        end
    
      end
    end

    describe "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested resource_permission" do
          resource_permission = BetterTogether::ResourcePermission.create! valid_attributes
          patch resource_permission_url(resource_permission), params: { resource_permission: new_attributes }
          resource_permission.reload
          skip("Add assertions for updated state")
        end

        it "redirects to the resource_permission" do
          resource_permission = BetterTogether::ResourcePermission.create! valid_attributes
          patch resource_permission_url(resource_permission), params: { resource_permission: new_attributes }
          resource_permission.reload
          expect(response).to redirect_to(resource_permission_url(resource_permission))
        end
      end

      context "with invalid parameters" do
    
        it "renders a response with 422 status (i.e. to display the 'edit' template)" do
          resource_permission = BetterTogether::ResourcePermission.create! valid_attributes
          patch resource_permission_url(resource_permission), params: { resource_permission: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_entity)
        end
    
      end
    end

    describe "DELETE /destroy" do
      it "destroys the requested resource_permission" do
        resource_permission = BetterTogether::ResourcePermission.create! valid_attributes
        expect {
          delete resource_permission_url(resource_permission)
        }.to change(BetterTogether::ResourcePermission, :count).by(-1)
      end

      it "redirects to the resource_permissions list" do
        resource_permission = BetterTogether::ResourcePermission.create! valid_attributes
        delete resource_permission_url(resource_permission)
        expect(response).to redirect_to(resource_permissions_url)
      end
    end
  end
end
