# frozen_string_literal: true

module BetterTogether
  # Gates ActiveStorage::DirectUploadsController#create behind a short-lived, signed
  # token proving the client actually rendered a page from this app recently -- raises
  # the bar above bare CSRF (which only proves *some* page was rendered, not
  # specifically an upload-capable one) without requiring authentication, since this
  # endpoint is used from pre-auth pages (sign-up, host-setup wizard) by design.
  #
  # The token is generated by ApplicationHelper#direct_upload_authorization_token,
  # embedded as a <meta name="direct-upload-token"> tag in every top-level layout, and
  # attached to each direct-upload request by JS listening for Rails' own
  # "direct-upload:before-blob-request" event (see
  # app/javascript/better_together/trix-extensions/richtext.js).
  #
  # Included into ActiveStorage::DirectUploadsController via the
  # active_storage_direct_upload_authorization initializer.
  module DirectUploadAuthorization
    extend ActiveSupport::Concern

    included do
      before_action :verify_direct_upload_token
    end

    private

    def verify_direct_upload_token
      token = request.headers['X-Direct-Upload-Token']

      unless token.present?
        head :unauthorized
        return
      end

      Rails.application.message_verifier(:direct_upload).verify(token)
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      head :unauthorized
    end
  end
end
