version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: activerecord
    versions:
    - 6.0.3.5
  - dependency-name: actionpack
    versions:
    - 6.0.3.5
  - dependency-name: faker
    versions:
    - 2.16.0
  - dependency-name: pry
    versions:
    - 0.14.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: rswag
    versions:
    - 2.3.2
    - 2.3.3
  - dependency-name: jsonapi-resources
    versions:
    - 0.10.3
  - dependency-name: capybara
    versions:
    - 3.35.1
