AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.4
plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot
Style/StringLiterals:
  Exclude:
    - 'db/migrate/*'

Rails:
  Enabled: false
Capybara:
  Enabled: false
FactoryBot:
  Enabled: false
