# This Dockerfile is used for the development environment via `docker compose`

FROM ruby:3.2.2

RUN apt-get update -qq \
  && apt-get install -y build-essential postgresql-client libpq-dev \
  nodejs libssl-dev apt-transport-https ca-certificates libvips42 nano

RUN mkdir /community-engine
WORKDIR /community-engine
COPY Gemfile /community-engine/Gemfile
COPY Gemfile.lock /community-engine/Gemfile.lock

RUN gem uninstall bundler
RUN gem install bundler:2.4.13

COPY . /community-engine
