graph TB
    Start([better_together:sitemap:refresh / SitemapRefreshJob]) --> CheckDB{Database<br/>available?}

    CheckDB -->|No| SkipDB[Log: database unavailable<br/>skip]
    CheckDB -->|Yes| PlatformScope[Platform.internal<br/>locally-hosted platforms]
    SkipDB --> End([End])

    PlatformScope -->|none| SkipPlatform[Log: no locally-hosted platform<br/>skip]
    PlatformScope -->|for each platform| Generator[Sitemaps::Generator.new platform]
    SkipPlatform --> End

    Generator --> ResolveHost[default_host =<br/>platform.resolved_host_url]
    ResolveHost --> LocaleLoop{For each locale<br/>en, es, fr, uk}

    LocaleLoop --> BuildLinkSet[Fresh SitemapGenerator::LinkSet<br/>public_path tmp/sitemaps/&lt;platform.id&gt;]
    BuildLinkSet --> AddResources[SitemapHelper.add_better_together_resources<br/>platform:]

    AddResources --> AddComm[Communities.for_platform.privacy_public]
    AddComm --> AddPost[Posts.for_platform.published.privacy_public]
    AddPost --> AddEvent[Events.for_platform.privacy_public]
    AddEvent --> AddPages[Pages.for_platform.published.privacy_public]

    AddPages --> AttachFile[attach_file_if_changed?<br/>Sitemap.current platform, locale]
    AttachFile --> MoreLocales{More locales?}
    MoreLocales -->|Yes| LocaleLoop
    MoreLocales -->|No| BuildIndex[Sitemaps::IndexBuilder<br/>&lt;loc&gt; = resolved_host_url/&lt;locale&gt;/sitemap.xml.gz]

    BuildIndex --> AttachIndex[attach_file_if_changed?<br/>Sitemap.current_index platform]
    AttachIndex --> Cleanup[Remove tmp/sitemaps/&lt;platform.id&gt;]
    Cleanup --> MorePlatforms{More platforms?}
    MorePlatforms -->|Yes| Generator
    MorePlatforms -->|No| End

    Generator -.->|Error| HandleError[Log error<br/>continue with next platform]
    HandleError --> MorePlatforms

    Serve[SitemapsController / RobotsTxtController] --> ResolvePlatform[Current.platform<br/>from request host]
    ResolvePlatform --> ServeFile[Redirect to that platform's<br/>Active Storage file]

    style Start fill:#e1f5e1
    style End fill:#ffe1e1
    style CheckDB fill:#fff3cd
    style AddComm fill:#d4edda
    style AddPost fill:#d4edda
    style AddEvent fill:#d4edda
    style AddPages fill:#d4edda
    style HandleError fill:#f8d7da
    style AttachFile fill:#cce5ff
    style AttachIndex fill:#cce5ff
