# frozen_string_literal: true

require 'rails_helper'

# rubocop:disable RSpec/DescribeClass
RSpec.describe 'Swagger generation integration' do
  let(:swagger_path) { BetterTogether::Engine.root.join('swagger/v1/swagger.yaml') }
  let(:swagger_content) { YAML.load_file(swagger_path) if File.exist?(swagger_path) }

  describe 'generated swagger documentation' do
    before do
      # Ensure swagger file exists (should be generated by rswag specs)
      skip 'Swagger file not generated' unless File.exist?(swagger_path)
    end

    it 'contains OpenAPI 3.0.1 specification' do
      expect(swagger_content['openapi']).to eq('3.0.1')
    end

    it 'contains API metadata' do
      expect(swagger_content['info']['title']).to eq('Community Engine API')
      expect(swagger_content['info']['version']).to eq('v1')
      expect(swagger_content['info']['description']).to include('Authentication')
    end

    it 'contains environment-aware server URL' do
      servers = swagger_content['servers']
      expect(servers).to be_an(Array)
      expect(servers).not_to be_empty

      server_urls = servers.map { |s| s['url'] }
      expect(server_urls).to include(BetterTogether.base_url)
    end

    it 'contains authentication security scheme' do
      bearer_auth = swagger_content.dig('components', 'securitySchemes', 'bearer_auth')

      expect(bearer_auth).not_to be_nil
      expect(bearer_auth['type']).to eq('http')
      expect(bearer_auth['scheme']).to eq('bearer')
      expect(bearer_auth['bearerFormat']).to eq('JWT')
    end

    it 'contains shared component schemas' do
      schemas = swagger_content.dig('components', 'schemas')

      expect(schemas).to include('ValidationErrors')
      expect(schemas).to include('User')
    end

    describe 'API paths documentation' do
      it 'contains authentication endpoints' do
        paths = swagger_content['paths']

        expect(paths).to include('/api/auth/sign-in')
        expect(paths).to include('/api/auth/sign-out')
        expect(paths).to include('/api/auth/sign-up')
        expect(paths).to include('/api/auth/password')
        expect(paths).to include('/api/auth/confirmation')
      end

      it 'contains v1 API endpoints' do
        paths = swagger_content['paths']

        expect(paths).to include('/api/v1/people')
        expect(paths).to include('/api/v1/people/{id}')
        expect(paths).to include('/api/v1/people/me')
        expect(paths).to include('/api/v1/communities')
        expect(paths).to include('/api/v1/communities/{id}')
        expect(paths).to include('/api/v1/roles')
        expect(paths).to include('/api/v1/roles/{id}')
      end

      it 'has at least 12 documented endpoints' do
        paths = swagger_content['paths']
        expect(paths.keys.length).to be >= 12
      end
    end

    describe 'authentication endpoint documentation' do
      it 'documents sign-in endpoint' do
        sign_in = swagger_content.dig('paths', '/api/auth/sign-in', 'post')

        expect(sign_in).not_to be_nil
        expect(sign_in['summary']).to include('Sign in')
        expect(sign_in['tags']).to include('Authentication')
        expect(sign_in['responses']).to include('200', '401')
      end

      it 'documents sign-out endpoint with authentication' do
        sign_out = swagger_content.dig('paths', '/api/auth/sign-out', 'delete')

        expect(sign_out).not_to be_nil
        expect(sign_out['security']).to include({ 'bearer_auth' => [] })
      end
    end

    describe 'v1 CRUD endpoint documentation' do
      it 'documents roles index endpoint' do
        roles_index = swagger_content.dig('paths', '/api/v1/roles', 'get')

        expect(roles_index).not_to be_nil
        expect(roles_index['summary']).to include('List all roles')
        expect(roles_index['tags']).to include('Roles')
        expect(roles_index['security']).to include({ 'bearer_auth' => [] })
      end

      it 'documents roles show endpoint with ID parameter' do
        roles_show = swagger_content.dig('paths', '/api/v1/roles/{id}', 'get')
        path_params = swagger_content.dig('paths', '/api/v1/roles/{id}', 'parameters')

        expect(roles_show).not_to be_nil
        expect(path_params).to be_an(Array)

        id_param = path_params.find { |p| p['name'] == 'id' }
        expect(id_param).not_to be_nil
        expect(id_param['in']).to eq('path')
        expect(id_param['required']).to be true
      end

      it 'documents people /me endpoint' do
        people_me = swagger_content.dig('paths', '/api/v1/people/me', 'get')

        expect(people_me).not_to be_nil
        expect(people_me['summary']).to include('current user')
        expect(people_me['security']).to include({ 'bearer_auth' => [] })
      end

      it 'documents communities CRUD endpoints' do
        communities_index = swagger_content.dig('paths', '/api/v1/communities', 'get')
        communities_create = swagger_content.dig('paths', '/api/v1/communities', 'post')
        communities_show = swagger_content.dig('paths', '/api/v1/communities/{id}', 'get')
        communities_update = swagger_content.dig('paths', '/api/v1/communities/{id}', 'patch')
        communities_delete = swagger_content.dig('paths', '/api/v1/communities/{id}', 'delete')

        expect(communities_index).not_to be_nil
        expect(communities_create).not_to be_nil
        expect(communities_show).not_to be_nil
        expect(communities_update).not_to be_nil
        expect(communities_delete).not_to be_nil
      end
    end

    describe 'response documentation' do
      it 'documents success responses' do
        sign_in = swagger_content.dig('paths', '/api/auth/sign-in', 'post')

        expect(sign_in['responses']['200']).not_to be_nil
        expect(sign_in['responses']['200']['description']).to be_present
      end

      it 'documents error responses' do
        sign_in = swagger_content.dig('paths', '/api/auth/sign-in', 'post')

        expect(sign_in['responses']['401']).not_to be_nil
        expect(sign_in['responses']['401']['description']).to include('invalid')
      end
    end
  end

  describe 'swagger file accessibility' do
    it 'is located in the engine swagger directory' do
      expect(swagger_path.to_s).to include('swagger/v1/swagger.yaml')
      expect(swagger_path.to_s).to start_with(
        BetterTogether::Engine.root.join('swagger').to_s
      )
    end

    it 'is a valid YAML file when it exists' do
      skip 'Swagger file not generated' unless File.exist?(swagger_path)

      expect { YAML.load_file(swagger_path) }.not_to raise_error
    end
  end
end
# rubocop:enable RSpec/DescribeClass
