# frozen_string_literal: true

require 'digest'

module BetterTogether
  module Seeds
    # Canonical seed envelope builder shared by local export and federated lanes.
    class Builder # rubocop:todo Metrics/ClassLength
      VERSION = '1.0'

      Result = Data.define(:seed_record, :seed_hash, :metadata)

      def self.call(**options)
        new(options).call
      end

      def initialize(options)
        @subject = options.fetch(:subject)
        @profile = options.fetch(:profile).to_s
        @actor = options[:actor]
        @context = (options[:context] || {}).with_indifferent_access
        @lane = options[:lane].presence || @profile
        @persist = options.fetch(:persist, false)
        @creator_id = options[:creator_id]
        @root_key = options.fetch(:root_key, BetterTogether::Seed::DEFAULT_ROOT_KEY)
        @version = options.fetch(:version, VERSION)
      end

      def call
        seed_hash = { root_key => envelope }

        Result.new(
          seed_record: persist? ? persist_seed!(seed_hash) : nil,
          seed_hash:,
          metadata: normalized_metadata
        )
      end

      private

      attr_reader :subject, :profile, :actor, :context, :lane, :creator_id, :root_key, :version

      def persist?
        @persist
      end

      def envelope
        {
          version:,
          seed: seed_metadata
        }.merge(payload_section)
      end

      def seed_metadata
        {
          type: 'BetterTogether::Seed',
          identifier: identifier,
          created_by: created_by,
          created_at: created_at.iso8601,
          description: description,
          origin: origin_attributes,
          seedable_type: seedable_type,
          seedable_id: seedable_id
        }
      end

      def payload_section
        if federated_subject?
          { payload: federated_payload }
        elsif context[:payload].present?
          { payload: context[:payload] }
        else
          { record: subject.plant }
        end
      end

      def origin_attributes
        base = {
          contributors: [],
          platforms: [],
          license: 'LGPLv3',
          usage_notes: usage_notes,
          lane:,
          profile:
        }

        return base.merge(federated_origin_attributes) if federated_subject?

        base.merge('export_root_key' => root_key)
      end

      def federated_origin_attributes
        connection = required_connection

        {
          source_platform_id: connection.source_platform.id,
          source_platform_identifier: connection.source_platform.identifier,
          source_platform_url: connection.source_platform.resolved_host_url,
          visibility: serialized_attributes[:privacy],
          content_type: serialized_type
        }.merge(context[:origin_metadata] || {})
      end

      def federated_payload
        {
          lane:,
          type: serialized_type,
          id: subject.id,
          preserve_remote_uuid: true,
          source_updated_at: subject.updated_at.iso8601,
          attributes: serialized_attributes
        }
      end

      def identifier
        return federated_identifier if federated_subject?

        context[:identifier].presence || "#{subject.class.name.demodulize.underscore}-#{subject.id}-#{SecureRandom.hex(4)}"
      end

      def federated_identifier
        connection = required_connection
        digest = Digest::SHA256.hexdigest(
          [connection.source_platform.id, subject.class.name, subject.id, lane].join(':')
        )
        "seed-#{serialized_type}-#{digest.first(24)}"
      end

      def created_by
        context[:created_by].presence || actor_label
      end

      def actor_label
        return 'FederatedExport' if federated_subject?

        actor.respond_to?(:identifier) ? actor.identifier : 'SystemExport'
      end

      def created_at
        context[:created_at].presence || (federated_subject? ? subject.updated_at.utc : Time.current.utc)
      end

      def description
        context[:description].presence || default_description
      end

      def default_description
        if federated_subject?
          "Federated seed for #{subject.class.name} #{subject.id}"
        else
          "Seed data for #{subject.class.name} record"
        end
      end

      def usage_notes
        return 'Generated by BetterTogether::Seeds::Builder for federated transport' if federated_subject?

        'Generated by BetterTogether::Seeds::Builder'
      end

      def seedable_type
        subject.class.name
      end

      def seedable_id
        subject.id
      end

      def persist_seed!(seed_hash) # rubocop:todo Metrics/AbcSize
        unless subject.persisted?
          raise ActiveRecord::RecordNotSaved,
                "Can't export seed from unsaved record (#{subject.class.name}). Save it first."
        end

        seed_association.create!(seed_record_attributes(seed_hash))
      end

      def seed_association
        return subject.seeds if subject.respond_to?(:seeds)

        ::BetterTogether::Seed.where(seedable: subject)
      end

      def seed_record_attributes(seed_hash)
        {
          type: 'BetterTogether::Seed',
          identifier: identifier,
          version:,
          created_by: created_by,
          creator_id: normalized_creator_id,
          seeded_at: created_at,
          seedable_type: seedable_type,
          seedable_id: seedable_id,
          description: description,
          origin: origin_attributes,
          payload: seed_hash
        }
      end

      def federated_subject?
        subject.is_a?(::BetterTogether::Post) ||
          subject.is_a?(::BetterTogether::Page) ||
          subject.is_a?(::BetterTogether::Event)
      end

      def required_connection
        context[:connection] || raise(ArgumentError, 'connection is required for federated seed building')
      end

      def serialized_type
        case subject
        when ::BetterTogether::Post then 'post'
        when ::BetterTogether::Page then 'page'
        when ::BetterTogether::Event then 'event'
        else
          raise ArgumentError, "unsupported record type: #{subject.class.name}"
        end
      end

      def serialized_attributes
        depth = context[:sync_depth].presence || 'standard'
        case subject
        when ::BetterTogether::Post then FederatedSeedAttributes.post_attributes(subject, sync_depth: depth)
        when ::BetterTogether::Page then FederatedSeedAttributes.page_attributes(subject, sync_depth: depth)
        when ::BetterTogether::Event then FederatedSeedAttributes.event_attributes(subject, sync_depth: depth)
        else
          {}
        end
      end

      def normalized_metadata
        {
          profile:,
          lane:,
          root_key:,
          version:,
          persisted: persist?,
          seedable_type:,
          seedable_id:
        }
      end

      def normalized_creator_id
        return unless creator_id.present?

        ::BetterTogether::Person.where(id: creator_id).pick(:id)
      end
    end
  end
end
