# frozen_string_literal: true

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'capybara/rspec'
require 'capybara-screenshot/rspec'
require 'simplecov'
require 'coveralls'
require 'rspec/rebound'
require 'webmock/rspec'
require 'parallel_rspec'

# Disable real external HTTP connections in tests but allow localhost so
# Capybara drivers (cuprite/ferrum/selenium) can communicate with the app
# server started by the test suite. Also allow Elasticsearch connections.
WebMock.disable_net_connect!(allow_localhost: true, allow: 'elasticsearch:9200')

# Monkey-patch RSpec profiler to handle nil durations gracefully (occurs with parallel_rspec)
module RSpec
  module Core
    module Formatters
      module Helpers
        class << self
          alias original_format_seconds format_seconds

          def format_seconds(float, precision = 2)
            return '0.00000' if float.nil?

            original_format_seconds(float, precision)
          end
        end
      end
    end
  end
end

# Allow CI/local runs to override coverage output to avoid permission issues
SimpleCov.coverage_dir ENV['SIMPLECOV_DIR'] if ENV['SIMPLECOV_DIR']

Capybara.asset_host = ENV.fetch('APP_HOST', 'http://localhost:3000')

Coveralls.wear!('rails')

formatters = [Coveralls::SimpleCov::Formatter]
formatters.unshift(SimpleCov::Formatter::HTMLFormatter) unless ENV['SIMPLECOV_NO_HTML'] == '1'
SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new(formatters)

# SimpleCov configuration lambda for parallel execution
# Each worker will call this with a unique worker number
simplecov_start = lambda do |worker_num = nil|
  # Set unique command name BEFORE starting SimpleCov
  SimpleCov.command_name worker_num ? "RSpec:Worker#{worker_num}" : 'RSpec'

  SimpleCov.start 'rails' do
    add_filter '/app/assets'
    add_filter '/app/javascript'
    add_filter '/app/views'
    add_filter '/bin/'
    add_filter '/config/'
    add_filter '/coverage/'
    add_filter '/db/'
    add_filter '/deploy/'
    add_filter '/docker/'
    add_filter '/docs/'
    add_filter '/log/'
    add_filter '/node_modules/'
    add_filter '/public/'
    add_filter '/script/'
    add_filter '/scripts/'
    add_filter '/spec/' # for rspec
    add_filter '/swagger/'
    add_filter '/tmp/'
    add_filter '/vendor/'

    # Architectural coverage groups
    add_group 'Builders', 'app/builders'
    add_group 'Forms', 'app/forms'
    add_group 'API Controllers', 'app/future_controllers/better_together'
    add_group 'Model Concerns', 'app/models/concerns'
    add_group 'Notifiers', 'app/notifiers'
    add_group 'Policies', 'app/policies'
    add_group 'Resources', 'app/resource'
    add_group 'Robots', 'app/robots'
    add_group 'Sanitizers', 'app/sanitizers'
    add_group 'Services', 'app/services'

    # ============================================================================
    # SUBSYSTEM COVERAGE GROUPS
    # Organized by Better Together Community Engine's 15 major functional systems
    # Based on: docs/assessments/architectural_analysis_2025-11.md
    # ============================================================================

    # Core Systems (High Priority)

    add_group '1. Platform Management' do |src_file|
      src_file.filename.match?(%r{
        /platform(?!_invitation)|
        /platforms_controller|
        /host_dashboard_controller|
        /platform_invitations_controller|
        /platform_policy|
        /platform_invitation_policy|
        /platform_invitation_mailer_job|
        /platform_host|
        /setup_wizard_controller|
        /setup_wizard_steps_controller|
        /settings_controller|
        /translations_controller|
        /help_preferences_controller
      }x) && !src_file.filename.match?(/person_platform_membership/)
    end

    add_group '2. Community Management' do |src_file|
      src_file.filename.match?(%r{
        /community(?!_collection)|
        /person_community_membership|
        /person_block|
        /report|
        /communities_controller|
        /person_community_memberships_controller|
        /person_blocks_controller|
        /reports_controller|
        /community_policy|
        /person_community_membership_policy|
        /person_block_policy|
        /report_policy|
        /primary_community|
        /hub_controller|
        /hub_policy|
        /member(?!ship)|
        /membership
      }x) && !src_file.filename.match?(/community_map/)
    end

    add_group '3. Content Management' do |src_file|
      src_file.filename.match?(%r{
        /page(?!_view|_metric)|
        /post(?!al)|
        /content/|
        /upload|
        /comment(?!able)|
        /pages_controller|
        /posts_controller|
        /uploads_controller|
        /static_pages_controller|
        /static_page_template_controller|
        /page_policy|
        /post_policy|
        /upload_policy|
        /author(?!ship)|
        /authorship|
        /publishing|
        /publishable
      }x)
    end

    add_group '4. Communication & Messaging' do |src_file|
      src_file.filename.match?(%r{
        /conversation|
        /message(?!_delivery)|
        /conversations_controller|
        /messages_controller|
        /conversation_policy|
        /message_policy|
        /conversations_channel|
        /messages_channel|
        /new_message_notifier
      }x)
    end

    add_group '5. Authentication & RBAC' do |src_file|
      src_file.filename.match?(%r{
        /user(?!_mailer)|
        /identification|
        /person(?!_community|_platform|_block|_checklist)|
        /people_controller|
        /person_policy|
        /guest_access|
        /guest_access_policy|
        /role(?!_resource)|
        /resource_permission|
        /role_resource_permission|
        /jwt_denylist|
        /users/|
        /roles_controller|
        /resource_permissions_controller|
        /role_policy|
        /resource_permission_policy|
        /user_policy|
        /permissible|
        /identity|
        /agent|
        /devise_user|
        /privacy|
        /protected|
        /visible
      }x)
    end

    add_group '6. Events & Calendar' do |src_file|
      src_file.filename.match?(%r{
        /event(?!_category_categorization)|
        /calendar(?!s_controller)|
        /calendar_event|
        /calendar_entry|
        /event_host|
        /events_controller|
        /calendars_controller|
        /events/|
        /event_policy|
        /event_attendance_policy|
        /event_invitation_policy|
        /event_category_policy|
        /calendar_policy|
        /event_reminder|
        /hosts_events
      }x)
    end

    add_group '7. Joatu Exchange' do |src_file|
      src_file.filename.match?(%r{
        /joatu/|
        /agreement(?!s_controller)|
        /agreements_controller|
        /agreement_policy|
        /call_for_interest|
        /calls_for_interest_controller|
        /call_for_interest_policy
      }x)
    end

    # Supporting Systems (Medium Priority)

    add_group '8. Geography & Location' do |src_file|
      src_file.filename.match?(%r{
        /geography/|
        /place(?!holder)
      }x)
    end

    add_group '9. Metrics & Analytics' do |src_file|
      src_file.filename.match?(%r{
        /page_view|
        /link_click|
        /metric(?!s_controller)|
        /metrics_controller|
        /metrics/|
        /trackable|
        /tracked_activity|
        /page_metrics|
        /activity_policy|
        /viewable
      }x)
    end

    add_group '10. Navigation System' do |src_file|
      src_file.filename.match?(%r{
        /navigation_area|
        /navigation_item|
        /navigation_areas_controller|
        /navigation_items_controller|
        /navigation_area_policy|
        /navigation_item_policy|
        /navigation_helper
      }x)
    end

    add_group '11. Notification System' do |src_file|
      src_file.filename.match?(%r{
        /notification(?!s_channel)|
        /notifiers/better_together/|
        /notifications_channel|
        /notifications_controller
      }x) && !src_file.filename.match?(/new_message_notifier|event_reminder/)
    end

    add_group '12. Content Organization' do |src_file|
      src_file.filename.match?(%r{
        /category(?!_categorization)|
        /tag(?!gable)|
        /friendly_slug|
        /categories_controller|
        /tags_controller|
        /category_policy|
        /sluggable|
        /categorizable|
        /search_controller|
        /searchable
      }x)
    end

    add_group '13. Contact Management' do |src_file|
      src_file.filename.match?(%r{
        /postal_address|
        /phone_number|
        /email_address|
        /social_media_account|
        /contact_detail|
        /address(?!able)|
        /postal_addresses_controller|
        /phone_numbers_controller|
        /email_addresses_controller|
        /postal_address_policy|
        /phone_number_policy|
        /email_address_policy|
        /social_media_account_policy|
        /contact_detail_policy|
        /address_policy|
        /website_link|
        /contactable
      }x)
    end

    # Specialized Systems (Lower Priority)

    add_group '14. Infrastructure System' do |src_file|
      src_file.filename.match?(%r{
        /building(?!_connection)|
        /building_connection|
        /floor|
        /room|
        /buildings_controller|
        /building_policy
      }x)
    end

    add_group '15. Workflow Management' do |src_file|
      src_file.filename.match?(%r{
        /wizard(?!_controller)|
        /wizards_controller|
        /wizard_steps_controller|
        /wizard_step(?!s_controller)|
        /wizard_step_definition|
        /checklist(?!s_controller)|
        /checklists_controller|
        /checklist_item(?!s_controller)|
        /checklist_items_controller|
        /person_checklist_item|
        /person_checklist_items_controller|
        /checklist_policy|
        /checklist_item_policy
      }x)
    end

    add_group '16. Invitations & Access' do |src_file|
      src_file.filename.match?(%r{
        /invitation(?!s_controller)|
        /invitations_controller
      }x)
    end
  end
end

# Configure SimpleCov for parallel or single execution
if defined?(ParallelRSpec)
  # Parallel execution: start SimpleCov in each worker with unique command name
  ParallelRSpec.configure do |config|
    config.after_fork do |worker_number|
      simplecov_start.call(worker_number)
    end
  end
else
  # Single execution: start SimpleCov immediately
  simplecov_start.call
end

RSpec.configure do |config|
  # show retry status in spec process
  config.verbose_retry = true
  # show exception that triggers a retry if verbose_retry is set to true
  config.display_try_failure_messages = true

  # run retry only on features
  config.around :each, type: :feature do |ex|
    ex.run_with_retry retry: 3
  end
  config.around :each, :js do |ex|
    ex.run_with_retry retry: 3
  end

  # Use Capybara’s DSL in feature specs
  config.include Capybara::DSL

  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.
  #   # This allows you to limit a spec run to individual examples or groups
  #   # you care about by tagging them with `:focus` metadata. When nothing
  #   # is tagged with `:focus`, all examples get run. RSpec also provides
  #   # aliases for `it`, `describe`, and `context` that include `:focus`
  #   # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  #   # config.filter_run_when_matching :focus
  #
  #   # Allows RSpec to persist some state between runs in order to support
  #   # the `--only-failures` and `--next-failure` CLI options. We recommend
  #   # you configure your source control system to ignore this file.
  #   # config.example_status_persistence_file_path = "spec/examples.txt"
  #
  #   # Limits the available syntax to the non-monkey patched syntax that is
  #   # recommended. For more details, see:
  #   #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   #   - http://www.rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
  #   # config.disable_monkey_patching!
  #
  #   # Many RSpec users commonly either run the entire suite or an individual
  #   # file, and it's useful to allow more verbose output when running an
  #   # individual spec file.
  #   # if config.files_to_run.one?
  #   #   # Use the documentation formatter for detailed output,
  #   #   # unless a formatter has already been configured
  #   #   # (e.g. via a command-line flag).
  #   #   config.default_formatter = "doc"
  #   # end
  #
  #   # Print the 10 slowest examples and example groups at the
  #   # end of the spec run, to help surface which specs are running
  #   # particularly slow.
  config.profile_examples = 5
  #
  #   # Run specs in random order to surface order dependencies. If you find an
  #   # order dependency and want to debug it, you can fix the order by providing
  #   # the seed, which is printed after each run.
  #   #     --seed 1234
  config.order = :random
  #
  #   # Seed global randomization in this process using the `--seed` CLI option.
  #   # Setting this allows you to use `--seed` to deterministically reproduce
  #   # test failures related to randomization by passing the same `--seed` value
  #   # as the one that triggered the failure.
  #   # Kernel.srand config.seed
end
