# frozen_string_literal: true

# rubocop:disable Metrics/ModuleLength, Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity, Metrics/BlockLength, Layout/LineLength, Style/CombinableLoops, Style/HashEachMethods

require 'fileutils'
require 'json'
require 'pathname'

Rails.application.eager_load!

# Generates subsystem-focused Mermaid and reference exports from live CE Rails reflections.
module CeSubsystemDiagramExport
  PROJECT_ROOT = Pathname.new(__dir__).join('..').expand_path
  GENERATED_HEADER = <<~TEXT
    <!--
      Generated by scripts/export_subsystem_diagrams.rb.
      Do not hand-edit the generated inventories or Mermaid sources without also updating the generator.
    -->
  TEXT

  ConcernCapability = Struct.new(:capability, :risk, :config_extractor)

  SUBSYSTEMS = [
    {
      key: 'identity_access',
      title: 'Identity, access, and memberships',
      prefix: 'ce_identity_access',
      description: 'People, users, identifications, invitations, roles, memberships, and privacy/export lifecycle records.',
      models: %w[
        BetterTogether::GuestAccess
        BetterTogether::Identification
        BetterTogether::Invitation
        BetterTogether::OauthAccessGrant
        BetterTogether::OauthAccessToken
        BetterTogether::OauthApplication
        BetterTogether::OauthUser
        BetterTogether::Person
        BetterTogether::PersonAccessGrant
        BetterTogether::PersonBlock
        BetterTogether::PersonChecklistItem
        BetterTogether::PersonCommunityMembership
        BetterTogether::PersonDataExport
        BetterTogether::PersonDeletionRequest
        BetterTogether::PersonLink
        BetterTogether::PersonLinkedSeed
        BetterTogether::PersonPlatformIntegration
        BetterTogether::PersonPlatformMembership
        BetterTogether::PersonPurgeAudit
        BetterTogether::ResourcePermission
        BetterTogether::Role
        BetterTogether::RoleResourcePermission
        BetterTogether::User
      ],
      controllers: %w[
        BetterTogether::InvitationsController
        BetterTogether::OauthApplicationsController
        BetterTogether::PeopleController
        BetterTogether::PersonAccessGrantsController
        BetterTogether::PersonBlocksController
        BetterTogether::PersonChecklistItemsController
        BetterTogether::PersonCommunityMembershipsController
        BetterTogether::PersonDataExportsController
        BetterTogether::PersonDeletionRequestsController
        BetterTogether::PersonLinkedSeedsController
        BetterTogether::PersonLinksController
        BetterTogether::PersonPlatformIntegrationsController
        BetterTogether::PersonPlatformMembershipsController
        BetterTogether::PersonSeedsController
        BetterTogether::ResourcePermissionsController
        BetterTogether::RolesController
        BetterTogether::UsersController
      ]
    },
    {
      key: 'platform_network',
      title: 'Platforms, communities, routing, and federation',
      prefix: 'ce_platform_network',
      description: 'Platforms, communities, domains, platform connections, storage, robots, routing, and host/app topology surfaces.',
      models: %w[
        BetterTogether::Community
        BetterTogether::CommunityInvitation
        BetterTogether::FederationAccessToken
        BetterTogether::NavigationArea
        BetterTogether::NavigationItem
        BetterTogether::Platform
        BetterTogether::PlatformConnection
        BetterTogether::PlatformDomain
        BetterTogether::PlatformInvitation
        BetterTogether::Robot
        BetterTogether::Sitemap
        BetterTogether::StorageConfiguration
        BetterTogether::Wizard
        BetterTogether::WizardStep
        BetterTogether::WizardStepDefinition
      ],
      controllers: %w[
        BetterTogether::CommunitiesController
        BetterTogether::CommunityWebhookEndpointsController
        BetterTogether::HostDashboardController
        BetterTogether::HubController
        BetterTogether::MembershipRequestsController
        BetterTogether::NavigationAreasController
        BetterTogether::NavigationItemsController
        BetterTogether::PlatformConnectionsController
        BetterTogether::PlatformInvitationsController
        BetterTogether::PlatformsController
        BetterTogether::SettingsController
        BetterTogether::SetupWizardController
        BetterTogether::SetupWizardStepsController
        BetterTogether::SitemapsController
        BetterTogether::StorageConfigurationsController
        BetterTogether::WizardStepsController
        BetterTogether::WizardsController
      ]
    },
    {
      key: 'content_publishing',
      title: 'Content, publishing, navigation, and claims',
      prefix: 'ce_content_publishing',
      description: 'Pages, posts, uploads, categories, citations, claims, comments, and the content block system.',
      model_prefixes: %w[
        BetterTogether::Content::
      ],
      models: %w[
        BetterTogether::Authorship
        BetterTogether::CallForInterest
        BetterTogether::Categorization
        BetterTogether::Category
        BetterTogether::Citation
        BetterTogether::Claim
        BetterTogether::Comment
        BetterTogether::EvidenceLink
        BetterTogether::Page
        BetterTogether::Post
        BetterTogether::Upload
      ],
      controllers: %w[
        BetterTogether::CallsForInterestController
        BetterTogether::CategoriesController
        BetterTogether::CitationExportsController
        BetterTogether::Content::BlocksController
        BetterTogether::GitHubCitationImportsController
        BetterTogether::GitHubContributionImportsController
        BetterTogether::PagesController
        BetterTogether::PostsController
        BetterTogether::StaticPageTemplateController
        BetterTogether::StaticPagesController
        BetterTogether::TranslationsController
        BetterTogether::UploadsController
      ]
    },
    {
      key: 'geography_and_places',
      title: 'Geography, addresses, and places',
      prefix: 'ce_geography_places',
      description: 'Addresses, places, and geospatial/location support classes that other subsystems depend on.',
      model_prefixes: %w[
        BetterTogether::Geography::
      ],
      models: %w[
        BetterTogether::Address
        BetterTogether::Place
      ],
      controllers: %w[
        BetterTogether::Geography::AddressesController
        BetterTogether::Geography::PlacesController
      ]
    },
    {
      key: 'events_calendar',
      title: 'Events, calendars, attendance, and invitations',
      prefix: 'ce_events_calendar',
      description: 'Event scheduling, recurrence, calendars, attendance, organizer flows, and invitation lifecycle.',
      models: %w[
        BetterTogether::Calendar
        BetterTogether::CalendarEntry
        BetterTogether::Event
        BetterTogether::EventAttendance
        BetterTogether::EventCategory
        BetterTogether::EventHost
        BetterTogether::EventInvitation
        BetterTogether::Occurrence
        BetterTogether::Recurrence
      ],
      controllers: %w[
        BetterTogether::CalendarsController
        BetterTogether::EventsController
      ]
    },
    {
      key: 'conversations_safety',
      title: 'Conversations, messaging, reports, and safety',
      prefix: 'ce_conversations_safety',
      description: 'Conversation threads, messages, moderation/report intake, and safety case review surfaces.',
      model_prefixes: %w[
        BetterTogether::Safety::
      ],
      models: %w[
        BetterTogether::Conversation
        BetterTogether::ConversationParticipant
        BetterTogether::Message
        BetterTogether::Report
      ],
      controllers: %w[
        BetterTogether::ConversationsController
        BetterTogether::MessagesController
        BetterTogether::ReportsController
        BetterTogether::Safety::CasesController
        BetterTogether::Safety::NotesController
      ]
    },
    {
      key: 'exchange_governance',
      title: 'Agreements, governance, exchange, and checklist flows',
      prefix: 'ce_exchange_governance',
      description: 'Agreement-driven governance, Joatu exchange models, checklist participation, and seed-based coordination.',
      model_prefixes: %w[
        BetterTogether::Joatu::
      ],
      models: %w[
        BetterTogether::Agreement
        BetterTogether::AgreementParticipant
        BetterTogether::AgreementTerm
        BetterTogether::Checklist
        BetterTogether::ChecklistItem
        BetterTogether::Seed
        BetterTogether::SeedPlanting
      ],
      controllers: %w[
        BetterTogether::AgreementsController
        BetterTogether::AgreementsStatusController
        BetterTogether::ChecklistItemsController
        BetterTogether::ChecklistsController
        BetterTogether::Joatu::AgreementsController
        BetterTogether::Joatu::OfferingsController
        BetterTogether::Joatu::OffersController
        BetterTogether::Joatu::RequestsController
        BetterTogether::SeedsController
      ]
    },
    {
      key: 'metrics_search_ai',
      title: 'Metrics, search, notifications, and AI support',
      prefix: 'ce_metrics_search_ai',
      description: 'Metrics records, search infrastructure, notification surfaces, and AI translation logging.',
      model_prefixes: %w[
        BetterTogether::Ai::
        BetterTogether::Metrics::
      ],
      models: %w[
        BetterTogether::Links
        BetterTogether::Notification
        BetterTogether::OneTimePrekey
      ],
      controllers: %w[
        BetterTogether::HelpPreferencesController
        BetterTogether::Metrics::LinksController
        BetterTogether::Metrics::SearchesController
        BetterTogether::NotificationsController
        BetterTogether::SearchController
        BetterTogether::ViewPreferencesController
      ]
    },
    {
      key: 'integrations_webhooks',
      title: 'Integrations, webhooks, API, and automation',
      prefix: 'ce_integrations_webhooks',
      description: 'Webhook endpoints, deliveries, API/controller concern surfaces, and automation entry points.',
      models: %w[
        BetterTogether::WebhookDelivery
        BetterTogether::WebhookEndpoint
      ],
      controllers: %w[
        BetterTogether::Api::BaseController
        BetterTogether::Api::JsonapiController
        BetterTogether::Api::V1::PlatformConnectionsController
        BetterTogether::Api::V1::PlatformsController
        BetterTogether::Api::V1::PostsController
        BetterTogether::Api::V1::WebhooksController
        BetterTogether::WebhookEndpointsController
      ]
    },
    {
      key: 'shared_supporting',
      title: 'Shared and supporting runtime surfaces',
      prefix: 'ce_shared_supporting',
      description: 'Live runtime classes that do not yet fit the primary subsystem taxonomy and should be reviewed for future extraction.'
    }
  ].freeze

  CONCERN_CAPABILITIES = {
    'BetterTogether::Authorable' => ConcernCapability.new(
      capability: 'Adds author/authorship associations and creator-aware authorship workflow.',
      risk: 'Author visibility and blocked-author behavior must stay aligned with policy scopes.'
    ),
    'BetterTogether::Categorizable' => ConcernCapability.new(
      capability: 'Adds category join models and category-aware filtering.',
      risk: 'Cross-subsystem joins can become noisy when categories span multiple content families.'
    ),
    'BetterTogether::Claimable' => ConcernCapability.new(
      capability: 'Adds claim/evidence linkage for governance, publishing, and provenance review.',
      risk: 'Weak evidence discipline can make claim graphs look authoritative without enough source context.'
    ),
    'BetterTogether::Contactable' => ConcernCapability.new(
      capability: 'Adds contact detail, website, phone, and social-link associations.',
      risk: 'Directory/admin surfaces can over-disclose private contact details if policies are too coarse.'
    ),
    'BetterTogether::Creatable' => ConcernCapability.new(
      capability: 'Adds creator ownership hooks and creator-aware defaults.',
      risk: 'Creator fallback behavior can accidentally widen operational visibility.'
    ),
    'BetterTogether::FriendlySlug' => ConcernCapability.new(
      capability: 'Adds translated/human-friendly slugs for routes and lookup.',
      risk: 'Slug uniqueness and routing ambiguity become cross-domain concerns when federation is involved.'
    ),
    'BetterTogether::Identifier' => ConcernCapability.new(
      capability: 'Adds canonical identifiers and slug/lookup helpers used across APIs and UI.',
      risk: 'Identifier reuse across platforms or mirrors can blur provenance without explicit platform context.'
    ),
    'BetterTogether::Invitable' => ConcernCapability.new(
      capability: 'Adds invitation lifecycle associations and invitee/inviter workflow hooks.',
      risk: 'Invitation authority is privacy-sensitive and should not piggyback on broad manager roles.'
    ),
    'BetterTogether::Joinable' => ConcernCapability.new(
      capability: 'Adds membership join models and membership-request helpers.',
      risk: 'Join/membership review surfaces can expose private community/member data if not scoped tightly.'
    ),
    'BetterTogether::Member' => ConcernCapability.new(
      capability: 'Adds person/community/platform membership associations and convenience helpers.',
      risk: 'Membership-derived access must stay community-scoped rather than falling back to global signed-in checks.'
    ),
    'BetterTogether::Permissible' => ConcernCapability.new(
      capability: 'Adds role/resource-permission linkage for policy checks and platform governance.',
      risk: 'Permission bundling can create god-mode reads unless capabilities are split carefully.'
    ),
    'BetterTogether::PrimaryCommunity' => ConcernCapability.new(
      capability: 'Adds default/host community linkage and delegation helpers.',
      risk: 'Host-community fallbacks are powerful and need careful tenant/platform context boundaries.'
    ),
    'BetterTogether::Privacy' => ConcernCapability.new(
      capability: 'Adds privacy enum helpers and shared visibility semantics.',
      risk: 'Shared helpers can over-broaden access when “community” or admin semantics drift.'
    ),
    'BetterTogether::Protected' => ConcernCapability.new(
      capability: 'Adds protected-record safeguards for records that should resist accidental mutation/deletion.',
      risk: 'Protected status can be mistaken for an authorization model when it is only a lifecycle safeguard.'
    ),
    'BetterTogether::Publishable' => ConcernCapability.new(
      capability: 'Adds publication timing/state helpers for user-facing publishing flows.',
      risk: 'Publish state can leak intent or draft timing if query scopes ignore privacy.'
    ),
    'BetterTogether::Searchable' => ConcernCapability.new(
      capability: 'Registers backend-neutral search contracts, pg_search wiring, and Elasticsearch callbacks.',
      risk: 'Search can become a visibility bypass if model scopes and indexed payloads drift.',
      config_extractor: lambda do |klass|
        parts = []
        if klass.respond_to?(:pg_search_enabled?)
          parts << "pg_search=#{klass.pg_search_enabled?}"
          parts << "scope=#{klass.search_scope_name}" if klass.search_scope_name
        end
        if klass.respond_to?(:global_searchable?)
          parts << "global_search=#{klass.global_searchable?}"
        end
        parts.join(', ')
      end
    ),
    'BetterTogether::Seedable' => ConcernCapability.new(
      capability: 'Adds seed/import/export helper behavior for reusable content and onboarding flows.',
      risk: 'Seed portability can carry stale permissions or provenance unless metadata stays explicit.'
    ),
    'BetterTogether::TimezoneAttributeAliasing' => ConcernCapability.new(
      capability: 'Adds consistent timezone aliases and coercion for scheduler-facing models.',
      risk: 'Hidden timezone aliasing can obscure which timestamps are canonical.'
    ),
    'BetterTogether::TrackedActivity' => ConcernCapability.new(
      capability: 'Adds PublicActivity hooks and activity-feed integration.',
      risk: 'Activity streams can reveal private operations if trackable scoping is too broad.'
    ),
    'BetterTogether::Viewable' => ConcernCapability.new(
      capability: 'Adds view-tracking hooks and reader-facing display helpers.',
      risk: 'View analytics and cache helpers can become privacy-sensitive telemetry surfaces.'
    ),
    'BetterTogether::WebhookPublishable' => ConcernCapability.new(
      capability: 'Adds webhook publication hooks for automation/integration events.',
      risk: 'Outbound publication surfaces carry secret and disclosure risk if endpoint access is too broad.'
    )
  }.freeze

  NOISY_COLUMNS = %w[id created_at updated_at lock_version discarded_at].freeze
  NOISY_VALIDATORS = %w[AssociatedValidator LengthValidator].freeze

  module_function

  def run!
    inventory = build_inventory
    write_inventory_exports(inventory)
    write_mermaid_exports(inventory)
  end

  def build_inventory
    subsystem_map = {}
    SUBSYSTEMS.each do |definition|
      subsystem_map[definition.fetch(:key)] = definition.merge(
        models_inventory: [],
        controllers_inventory: [],
        concerns_inventory: [],
        outbound_relationships: [],
        inbound_references: []
      )
    end

    model_concerns, controller_concerns = concern_constants
    models = collect_models
    controllers = collect_controllers

    model_lookup = models.index_by { |entry| entry.fetch(:name) }
    controller_lookup = controllers.index_by { |entry| entry.fetch(:name) }

    models.each do |model_entry|
      subsystem = subsystem_map.fetch(subsystem_for_model(model_entry.fetch(:name)).fetch(:key))
      subsystem[:models_inventory] << enrich_model_entry(model_entry, model_lookup, model_concerns)
    end

    controllers.each do |controller_entry|
      subsystem = subsystem_map.fetch(subsystem_for_controller(controller_entry.fetch(:name)).fetch(:key))
      subsystem[:controllers_inventory] << enrich_controller_entry(controller_entry, controller_lookup, controller_concerns)
    end

    subsystem_map.each_value do |subsystem|
      collect_subsystem_edges!(subsystem, subsystem_map)
      collect_concern_inventory!(subsystem)
      subsystem[:models_inventory].sort_by! { |entry| entry.fetch(:label) }
      subsystem[:controllers_inventory].sort_by! { |entry| entry.fetch(:label) }
      subsystem[:concerns_inventory].sort_by! { |entry| entry.fetch(:name) }
      subsystem[:outbound_relationships].uniq! { |edge| [edge[:from], edge[:to], edge[:label]] }
      subsystem[:inbound_references].uniq! { |edge| [edge[:from], edge[:to], edge[:label]] }
      annotate_shared_tables!(subsystem)
    end

    {
      generated_at: Time.current.iso8601,
      subsystems: subsystem_map.values
    }
  end

  def concern_constants
    [
      collect_modules(PROJECT_ROOT.join('app/models/concerns/better_together')),
      collect_modules(PROJECT_ROOT.join('app/controllers/concerns/better_together'))
    ]
  end

  def collect_modules(root)
    Dir[root.join('**/*.rb')].filter_map do |path|
      constant_name = constant_name_for_path(path, root)
      constant_name.safe_constantize
    end.compact
  end

  def collect_models
    ActiveRecord::Base.descendants.filter_map do |klass|
      next unless tracked_class?(klass)
      next if klass.abstract_class?

      {
        name: klass.name,
        label: klass.name.delete_prefix('BetterTogether::'),
        source_path: relative_source_path(klass),
        table_name: klass.table_name,
        columns: interesting_columns(klass),
        validations: validators_for(klass),
        belongs_to: belongs_to_relationships(klass),
        polymorphic: polymorphic_relationships(klass),
        translated_attributes: translated_attributes_for(klass)
      }
    end
  end

  def collect_controllers
    ActionController::Base.descendants.filter_map do |klass|
      next unless tracked_class?(klass)
      next unless relative_source_path(klass)&.start_with?('app/controllers/')

      {
        name: klass.name,
        label: klass.name.delete_prefix('BetterTogether::'),
        source_path: relative_source_path(klass),
        superclass: klass.superclass&.name,
        inferred_models: infer_controller_models(klass)
      }
    end
  end

  def tracked_class?(klass)
    klass.name&.start_with?('BetterTogether::')
  end

  def relative_source_path(klass)
    source = Object.const_source_location(klass.name)&.first
    return unless source

    Pathname.new(source).relative_path_from(PROJECT_ROOT).to_s
  rescue ArgumentError
    source
  end

  def interesting_columns(klass)
    klass.columns
         .reject { |column| NOISY_COLUMNS.include?(column.name) }
         .sort_by { |column| column_priority(column) }
         .first(10)
         .map do |column|
      [column.name, "#{column.type}#{' FK' if column.name.end_with?('_id')}"]
    end
  end

  def column_priority(column)
    [
      column.name.end_with?('_id') ? 0 : 1,
      %i[string text boolean integer datetime json jsonb].index(column.type) || 9,
      column.name
    ]
  end

  def validators_for(klass)
    klass.validators.filter_map do |validator|
      name = validator.class.name.demodulize
      next if NOISY_VALIDATORS.include?(name)

      options = validator.options.except(:class)
      summary = "#{name}: #{validator.attributes.join(', ')}"
      summary << " (#{format_validator_options(options)})" if options.present?
      summary
    end.uniq.first(8)
  end

  def format_validator_options(options)
    options.map do |key, value|
      rendered = value.is_a?(Proc) ? 'dynamic' : value.inspect
      "#{key}=#{rendered}"
    end.join(', ')
  end

  def translated_attributes_for(klass)
    attrs =
      if klass.respond_to?(:mobility_attributes)
        Array(klass.mobility_attributes).map(&:to_s)
      elsif klass.respond_to?(:translated_attribute_names)
        Array(klass.translated_attribute_names).map(&:to_s)
      else
        []
      end
    attrs.sort
  end

  def belongs_to_relationships(klass)
    klass.reflect_on_all_associations(:belongs_to).filter_map do |association|
      next if association.options[:polymorphic]

      target_name = association.klass&.name || normalize_model_name(association.class_name)
      next unless target_name

      {
        name: association.name.to_s,
        foreign_key: association.foreign_key.to_s,
        target: target_name,
        optional: association.options[:optional] == true
      }
    end
  end

  def polymorphic_relationships(klass)
    direct = klass.reflect_on_all_associations(:belongs_to).filter_map do |association|
      next unless association.options[:polymorphic]

      {
        direction: 'belongs_to',
        name: association.name.to_s,
        foreign_key: association.foreign_key.to_s,
        note: 'Polymorphic target set at runtime; foreign-key integrity is not enforced by the database.'
      }
    end

    inverse = klass.reflect_on_all_associations.filter_map do |association|
      next unless association.options[:as]

      {
        direction: association.macro.to_s,
        name: association.name.to_s,
        as: association.options[:as].to_s,
        note: 'Acts as a polymorphic owner surface; dependent classes point back through an interface column pair.'
      }
    end

    direct + inverse
  end

  def infer_controller_models(klass)
    candidates = []
    short_name = klass.name.delete_prefix('BetterTogether::').delete_suffix('Controller')
    candidates << "BetterTogether::#{short_name.singularize}" unless short_name.blank?

    if klass.name.include?('::')
      namespace_parts = klass.name.delete_prefix('BetterTogether::').delete_suffix('Controller').split('::')
      leaf = namespace_parts.pop
      namespace = namespace_parts.join('::')
      candidates << "BetterTogether::#{namespace}::#{leaf.singularize}" if namespace.present?
    end

    candidates.uniq.filter_map do |candidate|
      candidate.safe_constantize&.name
    end
  end

  def enrich_model_entry(entry, model_lookup, concern_constants)
    klass = entry.fetch(:name).constantize
    included_concerns = included_concerns_for(klass, concern_constants)
    entry.merge(
      concerns: included_concerns,
      concern_notes: included_concerns.filter_map { |concern_name| concern_configuration_for(klass, concern_name) },
      cross_subsystem_targets: entry.fetch(:belongs_to).filter_map do |association|
        target_name = association.fetch(:target)
        next unless model_lookup.key?(target_name)

        target_subsystem = subsystem_for_model(target_name).fetch(:key)
        next if target_subsystem == subsystem_for_model(entry.fetch(:name)).fetch(:key)

        association.merge(target_subsystem:)
      end
    )
  end

  def enrich_controller_entry(entry, _controller_lookup, concern_constants)
    klass = entry.fetch(:name).constantize
    included_concerns = included_concerns_for(klass, concern_constants)
    entry.merge(
      concerns: included_concerns,
      inferred_models: entry.fetch(:inferred_models).sort
    )
  end

  def included_concerns_for(klass, concern_constants)
    concern_constants.filter_map do |concern|
      concern_name = concern.name
      next unless concern_name
      next unless klass.ancestors.include?(concern)

      concern_name
    end.sort
  end

  def concern_configuration_for(klass, concern_name)
    definition = CONCERN_CAPABILITIES[concern_name]
    return unless definition&.config_extractor

    configuration = definition.config_extractor.call(klass)
    return if configuration.blank?

    "#{concern_name.delete_prefix('BetterTogether::')}: #{configuration}"
  end

  def subsystem_for_model(model_name)
    SUBSYSTEMS.find do |definition|
      Array(definition[:models]).include?(model_name) ||
        Array(definition[:model_prefixes]).any? { |prefix| model_name.start_with?(prefix) }
    end || fallback_subsystem(model_name, 'model')
  end

  def subsystem_for_controller(controller_name)
    SUBSYSTEMS.find do |definition|
      Array(definition[:controllers]).include?(controller_name) ||
        Array(definition[:controller_prefixes]).any? { |prefix| controller_name.start_with?(prefix) }
    end || fallback_subsystem(controller_name, 'controller')
  end

  def fallback_subsystem(name, kind)
    key = 'shared_supporting'
    fallback = SUBSYSTEMS.find { |definition| definition[:key] == key }
    return fallback if fallback

    raise "No subsystem mapping for #{kind} #{name.inspect}; add it to SUBSYSTEMS before exporting diagrams."
  end

  def collect_subsystem_edges!(subsystem, subsystem_map)
    subsystem[:models_inventory].each do |model_entry|
      model_entry.fetch(:cross_subsystem_targets).each do |association|
        subsystem[:outbound_relationships] << {
          from: model_entry.fetch(:name),
          to: association.fetch(:target),
          label: "#{association.fetch(:name)} (#{association.fetch(:foreign_key)})",
          target_subsystem: association.fetch(:target_subsystem)
        }
      end

      model_entry.fetch(:cross_subsystem_targets).each do |association|
        target_subsystem = subsystem_map.fetch(association.fetch(:target_subsystem))
        target_subsystem[:inbound_references] << {
          from: model_entry.fetch(:name),
          to: association.fetch(:target),
          label: "#{association.fetch(:name)} (#{association.fetch(:foreign_key)})",
          source_subsystem: subsystem.fetch(:key)
        }
      end
    end
  end

  def collect_concern_inventory!(subsystem)
    seen = Set.new

    subsystem[:models_inventory].each do |model_entry|
      model_entry.fetch(:concerns).each do |concern_name|
        next unless seen.add?([concern_name, 'model'])

        subsystem[:concerns_inventory] << concern_inventory_for(concern_name, subsystem[:models_inventory], :models_inventory)
      end
    end

    subsystem[:controllers_inventory].each do |controller_entry|
      controller_entry.fetch(:concerns).each do |concern_name|
        next unless seen.add?([concern_name, 'controller'])

        subsystem[:concerns_inventory] << concern_inventory_for(concern_name, subsystem[:controllers_inventory], :controllers_inventory)
      end
    end
  end

  def annotate_shared_tables!(subsystem)
    subsystem[:models_inventory]
      .group_by { |entry| entry.fetch(:table_name) }
      .each_value do |entries|
      next if entries.one?

      representative = shared_table_representative(entries)
      variants = entries.map { |entry| entry.fetch(:label) } - [representative.fetch(:label)]
      family_names = entries.map { |entry| entry.fetch(:name) }
      representative[:shared_table_variants] = variants
      representative[:shared_table_family_names] = family_names
      representative[:shared_table_group_size] = entries.size

      entries.each do |entry|
        next if entry.equal?(representative)

        entry[:shared_table_reference] = representative.fetch(:label)
        entry[:shared_table_reference_name] = representative.fetch(:name)
        entry[:shared_table_group_size] = entries.size
      end
    end
  end

  def shared_table_representative(entries)
    entries.min_by do |entry|
      klass = entry.fetch(:name).constantize
      [klass.base_class.name == klass.name ? 0 : 1, entry.fetch(:label).count(':'), entry.fetch(:label)]
    end
  end

  def concern_inventory_for(concern_name, entries, _kind)
    definition = CONCERN_CAPABILITIES[concern_name] || ConcernCapability.new(
      capability: concern_name.demodulize.tr('_', ' ').humanize,
      risk: 'Review the concern source for configuration-specific coupling or visibility implications.'
    )

    {
      name: concern_name,
      label: concern_name.delete_prefix('BetterTogether::'),
      capability: definition.capability,
      risk: definition.risk,
      included_by: entries.filter_map do |entry|
        entry.fetch(:label) if entry.fetch(:concerns).include?(concern_name)
      end
    }
  end

  def write_inventory_exports(inventory)
    reference_root = PROJECT_ROOT.join('docs/diagrams/reference')
    FileUtils.mkdir_p(reference_root)

    File.write(reference_root.join('ce_subsystem_inventory.json'), JSON.pretty_generate(inventory))
    File.write(reference_root.join('ce_subsystem_inventory.md'), inventory_markdown(inventory))
    File.write(reference_root.join('ce_concern_capability_assessment.md'), concern_markdown(inventory))
  end

  def write_mermaid_exports(inventory)
    source_root = PROJECT_ROOT.join('docs/diagrams/source')
    FileUtils.mkdir_p(source_root)

    inventory.fetch(:subsystems).each do |subsystem|
      File.write(source_root.join("#{subsystem.fetch(:prefix)}_schema_erd.mmd"), erd_mermaid(subsystem))
      File.write(source_root.join("#{subsystem.fetch(:prefix)}_rails_layers.mmd"), layers_mermaid(subsystem))
    end

    File.write(source_root.join('ce_subsystem_interaction_map.mmd'), interaction_map_mermaid(inventory))
    File.write(source_root.join('ce_polymorphic_association_map.mmd'), polymorphic_map_mermaid(inventory))
  end

  def inventory_markdown(inventory)
    lines = [GENERATED_HEADER.chomp, '# Community Engine subsystem inventory', '']
    lines << "Generated from live Rails reflections at `#{inventory.fetch(:generated_at)}`."
    lines << ''

    inventory.fetch(:subsystems).each do |subsystem|
      lines << "## #{subsystem.fetch(:title)}"
      lines << ''
      lines << subsystem.fetch(:description)
      lines << ''
      lines << "- Mermaid ERD: `docs/diagrams/source/#{subsystem.fetch(:prefix)}_schema_erd.mmd`"
      lines << "- Mermaid Rails layers: `docs/diagrams/source/#{subsystem.fetch(:prefix)}_rails_layers.mmd`"
      lines << ''
      lines << '### Models'
      lines << ''
      lines << '| Model | Table | Key attributes | Validations | Concerns | Cross-subsystem references |'
      lines << '| --- | --- | --- | --- | --- | --- |'
      subsystem.fetch(:models_inventory).each do |model_entry|
        lines << [
          model_entry.fetch(:label),
          "`#{model_entry.fetch(:table_name)}`",
          inventory_attribute_summary(model_entry),
          inventory_validation_summary(model_entry),
          truncate_join(model_entry.fetch(:concerns).map { |name| "`#{name.delete_prefix('BetterTogether::')}`" }),
          truncate_join(model_entry.fetch(:cross_subsystem_targets).map do |edge|
            "`#{edge.fetch(:name)}` -> `#{edge.fetch(:target).delete_prefix('BetterTogether::')}` (#{edge.fetch(:target_subsystem)})"
          end)
        ].map { |cell| cell.presence || '—' }.then { |cells| "| #{cells.join(' | ')} |" }
      end
      lines << ''
      lines << '### Controllers'
      lines << ''
      lines << '| Controller | Inherits from | Inferred models | Controller concerns |'
      lines << '| --- | --- | --- | --- |'
      subsystem.fetch(:controllers_inventory).each do |controller_entry|
        lines << [
          controller_entry.fetch(:label),
          "`#{controller_entry.fetch(:superclass)}`",
          truncate_join(controller_entry.fetch(:inferred_models).map { |name| "`#{name.delete_prefix('BetterTogether::')}`" }),
          truncate_join(controller_entry.fetch(:concerns).map { |name| "`#{name.delete_prefix('BetterTogether::')}`" })
        ].map { |cell| cell.presence || '—' }.then { |cells| "| #{cells.join(' | ')} |" }
      end
      lines << ''
      lines << '### Polymorphic / weak-reference surfaces'
      lines << ''
      subsystem_polymorphic = subsystem.fetch(:models_inventory).filter_map do |model_entry|
        next if model_entry.fetch(:polymorphic).empty?

        "- `#{model_entry.fetch(:label)}`: #{model_entry.fetch(:polymorphic).map { |edge| "`#{edge[:name]}` (#{edge[:direction]})" }.join(', ')}"
      end
      lines.concat(subsystem_polymorphic.presence || ['- None detected from direct reflections.'])
      lines << ''
      lines << '### Concern notes'
      lines << ''
      concern_notes = subsystem.fetch(:models_inventory).flat_map { |entry| entry.fetch(:concern_notes) }
      lines.concat(concern_notes.presence&.map { |note| "- #{note}" } || ['- No additional live concern configuration notes were extracted for this subsystem.'])
      lines << ''
    end

    lines.join("\n")
  end

  def concern_markdown(inventory)
    lines = [GENERATED_HEADER.chomp, '# Community Engine concern capability assessment', '']
    lines << 'This assessment is generated from the current live class set and the concern capability notes encoded in `scripts/export_subsystem_diagrams.rb`.'
    lines << ''
    lines << '| Concern | Capability | Included by live classes | Drawbacks / risks |'
    lines << '| --- | --- | --- | --- |'

    inventory.fetch(:subsystems)
             .flat_map { |subsystem| subsystem.fetch(:concerns_inventory) }
             .uniq { |entry| entry.fetch(:name) }
             .sort_by { |entry| entry.fetch(:label) }
             .each do |entry|
      lines << [
        "`#{entry.fetch(:label)}`",
        entry.fetch(:capability),
        truncate_join(entry.fetch(:included_by).map { |name| "`#{name}`" }, separator: ', '),
        entry.fetch(:risk)
      ].then { |cells| "| #{cells.join(' | ')} |" }
    end

    lines.join("\n")
  end

  def inventory_attribute_summary(model_entry)
    if model_entry[:shared_table_reference]
      "Shares `#{model_entry.fetch(:table_name)}` columns with `#{model_entry.fetch(:shared_table_reference)}`"
    else
      summary = truncate_join(model_entry.fetch(:columns).map { |name, type| "`#{name}` (#{type})" })
      variants = Array(model_entry[:shared_table_variants])
      return summary if variants.empty?

      [summary, "STI variants: #{summarize_labels(variants.map { |label| "`#{label}`" }, limit: 8)}"].join('<br>')
    end
  end

  def inventory_validation_summary(model_entry)
    return "Shares validation surface with `#{model_entry.fetch(:shared_table_reference)}`" if model_entry[:shared_table_reference]

    truncate_join(model_entry.fetch(:validations))
  end

  def erd_mermaid(subsystem)
    lines = ['%% Generated by scripts/export_subsystem_diagrams.rb', 'erDiagram']
    seen_edges = Set.new

    subsystem.fetch(:models_inventory).each do |model_entry|
      entity_name = erd_entity_name(model_entry.fetch(:table_name))
      model_entry.fetch(:belongs_to).each do |association|
        target_name = association.fetch(:target)
        target_entity = if target_name.start_with?('BetterTogether::') && tracked_model_name?(target_name)
                          target_subsystem = subsystem_for_model(target_name)
                          if target_subsystem.fetch(:key) == subsystem.fetch(:key)
                            erd_entity_name(model_entity_for(target_name).fetch(:table_name))
                          else
                            external_erd_entity_name(target_subsystem.fetch(:key), target_name)
                          end
                        else
                          generic_external_erd_entity_name(target_name)
                        end
        relation = association.fetch(:optional) ? 'o|--o{' : '||--o{'
        edge_key = [target_entity, relation, entity_name, association.fetch(:name), association.fetch(:foreign_key)]
        next unless seen_edges.add?(edge_key)

        lines << "  #{target_entity} #{relation} #{entity_name} : \"#{association.fetch(:name)} / #{association.fetch(:foreign_key)}\""
      end
    end

    lines << ''
    subsystem.fetch(:models_inventory)
             .uniq { |entry| entry.fetch(:table_name) }
             .each do |model_entry|
      lines.concat(erd_entity_block(model_entry))
      lines << ''
    end

    external_targets = subsystem.fetch(:outbound_relationships).group_by { |edge| [edge.fetch(:target_subsystem), edge.fetch(:to)] }
    external_targets.each do |(target_subsystem_key, target_name), _edges|
      lines.concat(external_entity_block(target_subsystem_key, target_name))
      lines << ''
    end

    subsystem.fetch(:models_inventory)
             .flat_map { |entry| entry.fetch(:belongs_to).map { |association| association.fetch(:target) } }
             .uniq
             .reject { |target_name| target_name.start_with?('BetterTogether::') && tracked_model_name?(target_name) }
             .each do |target_name|
      lines.concat(generic_external_entity_block(target_name))
      lines << ''
    end

    lines.join("\n")
  end

  def erd_entity_block(model_entry)
    lines = ["  #{erd_entity_name(model_entry.fetch(:table_name))} {"]
    model_entry.fetch(:columns).each do |name, type|
      lines << "    #{name} #{mermaid_type(type)}"
    end
    lines << '  }'
    lines
  end

  def external_entity_block(target_subsystem_key, target_name)
    [
      "  #{external_erd_entity_name(target_subsystem_key, target_name)} {",
      '    string export_ref',
      '  }'
    ]
  end

  def mermaid_type(type)
    type.to_s.split.first
  end

  def layers_mermaid(subsystem)
    lines = ['%% Generated by scripts/export_subsystem_diagrams.rb', 'classDiagram', '  direction LR', '']
    append_namespace(lines, 'Controllers') do
      subsystem.fetch(:controllers_inventory).map do |controller_entry|
        inferred_models = controller_entry.fetch(:inferred_models).map { |model_name| diagram_model_entry(subsystem, model_name) }.compact.uniq
        class_block(
          safe_id(controller_entry.fetch(:name)),
          controller_entry.fetch(:label),
          controller_block_attributes(controller_entry, inferred_models),
          indent: 4
        )
      end
    end
    append_namespace(lines, 'Models') do
      diagram_model_entries(subsystem).map do |model_entry|
        class_block(
          safe_id(model_entry.fetch(:name)),
          model_diagram_label(model_entry),
          model_block_attributes(subsystem, model_entry),
          indent: 4
        )
      end
    end

    external_models = diagram_model_entries(subsystem).flat_map do |entry|
      family_entries(subsystem, entry).flat_map { |family_entry| family_entry.fetch(:belongs_to).map { |association| association.fetch(:target) } }
    end
    external_models.concat(
      subsystem.fetch(:outbound_relationships).map { |edge| edge.fetch(:to) }
    )
    external_models.uniq!
    external_models.reject! { |target_name| target_name.start_with?('BetterTogether::') && tracked_model_name?(target_name) }
    unless external_models.empty?
      lines << '  namespace ExternalSubsystems {'
      external_models.each do |model_name|
        label =
          if model_name.start_with?('BetterTogether::') && tracked_model_name?(model_name)
            target_subsystem = subsystem_for_model(model_name)
            "#{model_name.delete_prefix('BetterTogether::')}\\n(#{target_subsystem.fetch(:key)})"
          else
            "#{model_name}\\n(external dependency)"
          end
        lines.concat(class_block(safe_id(model_name), label, ['<<External model>>'], indent: 4))
      end
      lines << '  }'
      lines << ''
    end

    seen_controller_edges = Set.new
    subsystem.fetch(:controllers_inventory).each do |controller_entry|
      controller_id = safe_id(controller_entry.fetch(:name))
      controller_entry.fetch(:inferred_models).each do |model_name|
        model_entry = diagram_model_entry(subsystem, model_name)
        next unless model_entry
        next unless seen_controller_edges.add?([controller_id, model_entry.fetch(:name)])

        lines << "  #{controller_id} ..> #{safe_id(model_entry.fetch(:name))} : manages"
      end
      if controller_entry.fetch(:superclass)&.start_with?('BetterTogether::')
        lines << "  #{controller_id} --|> #{safe_id(controller_entry.fetch(:superclass))}"
      end
    end

    seen_model_edges = Set.new
    diagram_model_entries(subsystem).each do |model_entry|
      model_id = safe_id(model_entry.fetch(:name))
      family_entries(subsystem, model_entry).each do |family_entry|
        family_entry.fetch(:belongs_to).each do |association|
          target_model_entry = diagram_model_entry(subsystem, association.fetch(:target))
          target_id = safe_id(target_model_entry ? target_model_entry.fetch(:name) : association.fetch(:target))
          edge_key = [model_id, target_id, association.fetch(:name)]
          next unless seen_model_edges.add?(edge_key)

          lines << "  #{model_id} --> #{target_id} : #{association.fetch(:name)}"
        end
      end
    end

    lines.join("\n")
  end

  def append_namespace(lines, name)
    blocks = Array(yield)
    return if blocks.empty?

    lines << "  namespace #{name} {"
    blocks.each { |block_lines| lines.concat(block_lines) }
    lines << '  }'
    lines << ''
  end

  def class_block(id, label, lines, indent:)
    spacing = ' ' * indent
    [
      "#{spacing}class #{id}[\"#{label}\"] {",
      *lines.map { |line| "#{spacing}  #{line}" },
      "#{spacing}}"
    ]
  end

  def interaction_map_mermaid(inventory)
    lines = ['%% Generated by scripts/export_subsystem_diagrams.rb', 'flowchart LR']

    inventory.fetch(:subsystems).each do |subsystem|
      lines << "  #{safe_id(subsystem.fetch(:key))}[\"#{subsystem.fetch(:title)}\"]"
    end
    lines << ''

    edge_counts = Hash.new(0)
    inventory.fetch(:subsystems).each do |subsystem|
      subsystem.fetch(:outbound_relationships).each do |edge|
        key = [subsystem.fetch(:key), edge.fetch(:target_subsystem)]
        edge_counts[key] += 1
      end
    end

    edge_counts.sort.each do |(from, to), count|
      lines << "  #{safe_id(from)} -->|#{count} cross-subsystem refs| #{safe_id(to)}"
    end

    lines.join("\n")
  end

  def polymorphic_map_mermaid(inventory)
    lines = ['%% Generated by scripts/export_subsystem_diagrams.rb', '%% render.orientation: portrait', 'flowchart TB']
    ordering_nodes = []

    inventory.fetch(:subsystems).each do |subsystem|
      lines << "  subgraph #{safe_id(subsystem.fetch(:key))}[\"#{subsystem.fetch(:title)}\"]"
      lines << '    direction TB'
      polymorphic_nodes = polymorphic_summary_nodes(subsystem)
      anchor_id = safe_id("#{subsystem.fetch(:key)}_polymorphic_anchor")
      if polymorphic_nodes.empty?
        none_id = safe_id("#{subsystem.fetch(:key)}_none")
        lines << "    #{none_id}[\"No polymorphic or weak-reference surfaces detected\"]"
        lines << "    #{anchor_id}:::hidden"
        lines << "    #{anchor_id} ~~~ #{none_id}"
      else
        lines << "    #{anchor_id}:::hidden"
        polymorphic_nodes.each do |node|
          lines << "    #{node.fetch(:id)}[\"#{node.fetch(:label)}\"]"
        end
        lines << "    #{anchor_id} ~~~ #{polymorphic_nodes.first.fetch(:id)}"
        polymorphic_nodes.each_cons(2) do |from, to|
          lines << "    #{from.fetch(:id)} ~~~ #{to.fetch(:id)}"
        end
      end
      lines << '  end'
      lines << ''
      ordering_nodes << anchor_id
    end

    ordering_nodes.each_cons(2) do |from, to|
      lines << "  #{from} ~~~ #{to}"
    end

    lines << '  classDef hidden fill:none,stroke:none,color:transparent;'
    lines << '  RiskNote["Polymorphic edges are flexible integration points, but they do not have strong foreign-key enforcement. Review allowlists, dependent behavior, and authorization around every polymorphic surface."]'
    lines.join("\n")
  end

  def model_entity_for(model_name)
    @model_entity_lookup ||= collect_models.index_by { |entry| entry.fetch(:name) }
    @model_entity_lookup.fetch(model_name)
  end

  def diagram_model_entries(subsystem)
    subsystem.fetch(:models_inventory).reject { |entry| entry[:shared_table_reference] }
  end

  def diagram_model_entry(subsystem, model_name)
    model_entry = subsystem.fetch(:models_inventory).find { |entry| entry.fetch(:name) == model_name }
    return unless model_entry
    return model_entry unless model_entry[:shared_table_reference_name]

    subsystem.fetch(:models_inventory).find { |entry| entry.fetch(:name) == model_entry.fetch(:shared_table_reference_name) }
  end

  def family_entries(subsystem, model_entry)
    family_names = Array(model_entry[:shared_table_family_names]).presence || [model_entry.fetch(:name)]
    subsystem.fetch(:models_inventory).select { |entry| family_names.include?(entry.fetch(:name)) }
  end

  def controller_block_attributes(controller_entry, inferred_models)
    attributes = ['<<Controller>>']
    labels = inferred_models.map { |entry| entry.fetch(:label) }
    attributes << "models: #{summarize_labels(labels)}" if labels.present?
    concern_labels = controller_entry.fetch(:concerns).map { |name| name.delete_prefix('BetterTogether::') }
    attributes << "concerns: #{summarize_labels(concern_labels)}" if concern_labels.present?
    attributes
  end

  def model_diagram_label(model_entry)
    return model_entry.fetch(:label) if Array(model_entry[:shared_table_variants]).empty?

    "#{model_entry.fetch(:label)}\\n(shared table family)"
  end

  def model_block_attributes(subsystem, model_entry)
    entries = family_entries(subsystem, model_entry)
    concern_labels = entries.flat_map { |entry| entry.fetch(:concerns) }.uniq.map { |name| name.delete_prefix('BetterTogether::') }
    translated = entries.flat_map { |entry| entry.fetch(:translated_attributes) }.uniq
    weak_links = entries.flat_map { |entry| entry.fetch(:polymorphic).map { |edge| polymorphic_surface_label(edge) } }.uniq
    attributes = [
      '<<Model>>',
      "table: #{model_entry.fetch(:table_name)}"
    ]
    if entries.size > 1
      variant_labels = entries.map { |entry| entry.fetch(:label) } - [model_entry.fetch(:label)]
      attributes << "variants: #{summarize_labels(variant_labels, limit: 5)}"
    end
    attributes << "translates: #{summarize_labels(translated)}" if translated.present?
    attributes << "concerns: #{summarize_labels(concern_labels)}" if concern_labels.present?
    attributes << "weak refs: #{summarize_labels(weak_links)}" if weak_links.present?
    attributes
  end

  def polymorphic_summary_nodes(subsystem)
    diagram_model_entries(subsystem).filter_map do |model_entry|
      entries = family_entries(subsystem, model_entry)
      surfaces = entries.flat_map { |entry| entry.fetch(:polymorphic) }
      next if surfaces.empty?

      labels = surfaces.map { |edge| polymorphic_surface_label(edge) }.uniq
      family_suffix =
        if entries.size > 1
          "\\nfamily: #{entries.size} models"
        else
          ''
        end

      {
        id: safe_id("#{model_entry.fetch(:name)}_polymorphic_summary"),
        label: "#{model_entry.fetch(:label)}#{family_suffix}\\n#{summarize_labels(labels, limit: 5)}"
      }
    end
  end

  def polymorphic_surface_label(edge)
    prefix = edge.fetch(:direction) == 'belongs_to' ? 'target' : 'owner'
    "#{prefix}: #{edge.fetch(:name)}"
  end

  def summarize_labels(values, limit: 4)
    return if values.blank?

    labels = values.compact.uniq
    return labels.join(', ') if labels.size <= limit

    "#{labels.first(limit).join(', ')} +#{labels.size - limit}"
  end

  def tracked_model_name?(model_name)
    @tracked_model_names ||= collect_models.to_set { |entry| entry.fetch(:name) }
    @tracked_model_names.include?(model_name)
  end

  def normalize_model_name(name)
    return if name.blank?
    return name if name.start_with?('BetterTogether::')

    "BetterTogether::#{name}".safe_constantize&.name || name.safe_constantize&.name
  end

  def truncate_join(values, separator: '<br>')
    return if values.blank?

    values.first(6).join(separator)
  end

  def constant_name_for_path(path, root)
    relative = Pathname.new(path).relative_path_from(root).to_s
    "BetterTogether::#{relative.delete_suffix('.rb').split('/').map(&:camelize).join('::')}"
  end

  def safe_id(value)
    value.to_s.gsub(/[^A-Za-z0-9]/, '_')
  end

  def compact_erd_token(value)
    value.to_s
         .sub(/\Abetter_together_/, '')
         .sub(/\Ametrics_/, '')
         .sub(/\Ageography_/, '')
         .gsub(/[^A-Za-z0-9]/, '_')
         .upcase
  end

  def compact_external_erd_token(model_name)
    model_name.to_s
              .delete_prefix('BetterTogether::')
              .underscore
              .gsub(%r{/}, '_')
              .gsub(/[^A-Za-z0-9]/, '_')
              .gsub(/_+/, '_')
              .upcase
  end

  def erd_entity_name(table_name)
    compact_erd_token(table_name)
  end

  def external_erd_entity_name(_subsystem_key, model_name)
    "EXT_#{compact_external_erd_token(model_name)}"
  end

  def generic_external_erd_entity_name(model_name)
    "EXT_#{compact_external_erd_token(model_name)}"
  end

  def generic_external_entity_block(model_name)
    [
      "  #{generic_external_erd_entity_name(model_name)} {",
      '    string external_reference',
      '  }'
    ]
  end
end

CeSubsystemDiagramExport.run!
# rubocop:enable Metrics/ModuleLength, Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity, Metrics/BlockLength, Layout/LineLength, Style/CombinableLoops, Style/HashEachMethods
