#!/usr/bin/env bash
set -euo pipefail

# Builds a single PDF from the docs/ tree by following docs/table_of_contents.md ordering.
# Requirements: pandoc, a LaTeX engine (defaults to xelatex).

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="${DOCS_DIR:-"$ROOT_DIR/docs"}"
TOC_FILE="${TOC_FILE:-"$DOCS_DIR/table_of_contents.md"}"
BUILD_DIR="${BUILD_DIR:-"$ROOT_DIR/build/docs"}"
TEMP_MD="$BUILD_DIR/combined.md"
OUTPUT_PDF="${OUTPUT_PDF:-"$BUILD_DIR/community-engine-guide.pdf"}"
PDF_ENGINE="${PDF_ENGINE:-xelatex}"
HEADER_TEX="$BUILD_DIR/pandoc-header.tex"
MAIN_FONT="${MAIN_FONT:-Noto Sans}"
SANS_FONT="${SANS_FONT:-Noto Sans}"
MONO_FONT="${MONO_FONT:-Noto Sans Mono}"
EMOJI_FONT="${EMOJI_FONT:-Noto Sans Symbols2}"
CJK_FONT="${CJK_FONT:-Noto Sans CJK SC}"
STAKEHOLDER_GROUPS="${STAKEHOLDER_GROUPS:-end_users community_organizers platform_organizers developers support_staff content_moderators legal_compliance}"

if ! command -v pandoc >/dev/null 2>&1; then
  echo "pandoc is required but not found on PATH" >&2
  exit 1
fi

mkdir -p "$BUILD_DIR"

# Extract ordered markdown paths from the table of contents (Python for portability).
mapfile -t DOC_FILES < <(python3 - "$TOC_FILE" <<'PY'
import re, sys, pathlib

toc_path = pathlib.Path(sys.argv[1])
pattern = re.compile(r'\]\(([^)]+\.md)\)')

for line in toc_path.read_text(encoding="utf-8").splitlines():
    match = pattern.search(line)
    if match:
        print(match.group(1))
PY
)

# Allow deep nested lists in the generated LaTeX.
cat > "$HEADER_TEX" <<TEX
\usepackage{enumitem}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX,Renderer=Harfbuzz,Scale=MatchLowercase}
\setmainfont{${MAIN_FONT}}
\setsansfont{${SANS_FONT}}
\setmonofont{${MONO_FONT}}
\newfontfamily\CJKmainfont[Path=/usr/share/fonts/opentype/noto/,Extension=.ttc,Renderer=Harfbuzz]{NotoSansCJK-Regular}
\newfontfamily\EmojiFont[Renderer=Harfbuzz]{${EMOJI_FONT}}
\setlistdepth{9}
\renewlist{itemize}{itemize}{9}
\renewlist{enumerate}{enumerate}{9}
\setlist[itemize]{leftmargin=*}
\setlist[enumerate]{leftmargin=*}
\setlist[itemize,1]{label=$\bullet$}
\setlist[itemize,2]{label=$\circ$}
\setlist[itemize,3]{label=$\triangleright$}
\setlist[itemize,4]{label=$\cdot$}
\setlist[itemize,5]{label=$\diamond$}
\setlist[itemize,6]{label=$\ast$}
\setlist[itemize,7]{label=$\dagger$}
\setlist[itemize,8]{label=$\ddagger$}
\setlist[itemize,9]{label=$\star$}
\setlist[enumerate,1]{label=\arabic*.)}
\setlist[enumerate,2]{label=\alph*.)}
\setlist[enumerate,3]{label=\roman*.)}
\setlist[enumerate,4]{label=\Alph*.)}
\setlist[enumerate,5]{label=\Roman*.)}
\setlist[enumerate,6]{label=\arabic*.)}
\setlist[enumerate,7]{label=\alph*.)}
\setlist[enumerate,8]{label=\roman*.)}
\setlist[enumerate,9]{label=\Alph*.)}
\pagenumbering{arabic}
\setcounter{page}{1}
\pagestyle{plain}
TEX

build_pdf() {
  local label="$1"
  local output_pdf="$2"
  shift 2
  local files=("$@")
  local temp_md="$BUILD_DIR/${label}.md"

  cat > "$temp_md" <<HEADER
% Better Together Community Engine Guide
% Auto-generated (${label})
% \today

## Overview

This PDF bundles the primary Community Engine documentation for ${label}. Source of truth remains the repository markdown; diagrams should be re-rendered before export.

<!-- TOC will be generated by pandoc -->
HEADER

  for doc in "${files[@]}"; do
    DOC_PATH="$DOCS_DIR/$doc"
    if [[ ! -f "$DOC_PATH" ]]; then
      echo "Skipping missing doc referenced in TOC: $doc" >&2
      continue
    fi

    {
      echo
      echo
      cat "$DOC_PATH"
    } >> "$temp_md"
  done

  pandoc "$temp_md" \
    --from=gfm \
    --toc --toc-depth=3 \
    --pdf-engine="$PDF_ENGINE" \
    --include-in-header="$HEADER_TEX" \
    -V geometry:margin=1in \
    -o "$output_pdf"

  echo "Built PDF: $output_pdf"
}

if [[ ${#DOC_FILES[@]} -eq 0 ]]; then
  echo "No markdown files found in $TOC_FILE" >&2
  exit 1
fi

# Build combined guide
build_pdf "combined" "$OUTPUT_PDF" "${DOC_FILES[@]}"

# Build per-stakeholder guides
for group in $STAKEHOLDER_GROUPS; do
  group_docs=()
  for doc in "${DOC_FILES[@]}"; do
    [[ "$doc" == "${group}/"* ]] && group_docs+=("$doc")
  done

  if [[ ${#group_docs[@]} -eq 0 ]]; then
    echo "No docs for stakeholder group: $group (skipping)" >&2
    continue
  fi

  build_pdf "$group" "$BUILD_DIR/community-engine-guide-${group}.pdf" "${group_docs[@]}"
done
