# frozen_string_literal: true

module BetterTogether
  # Provisions a federation connection between two platforms in a single transaction.
  #
  # Handles:
  #   - PlatformConnection creation (OAuth credentials auto-generated by model callback)
  #   - Connection policy configuration (content sharing + auth scopes)
  #   - Connection mode: :request (pending, awaiting target approval) or :auto_accept (immediately active)
  #   - Sync job dispatch when auto-accepted
  #
  # Idempotent: uses find_or_initialize_by(source_platform:, target_platform:).
  # Calling with the same platform pair updates policies rather than duplicating.
  #
  # Modes:
  #   :request (default) — Creates a pending connection. The target platform's organizers
  #     must independently approve it. Use this when inviting an independently-managed platform.
  #
  #   :auto_accept — Creates the connection AND immediately activates it on behalf of both
  #     platforms. Only use this when the provisioner has authority over both platforms
  #     (e.g. a host org provisioning a sub-tenant it fully manages).
  #
  # Usage:
  #   # Invite an independent peer (requires their approval):
  #   result = BetterTogether::FederationConnectionProvisioningService.call(
  #     source_platform: local_platform,
  #     target_platform: peer_platform,
  #     policies: { content_sharing_policy: 'mirror_network_feed', federation_auth_policy: 'api_read' }
  #   )
  #
  #   # Provision a managed sub-tenant (auto-accept on both sides):
  #   result = BetterTogether::FederationConnectionProvisioningService.call(
  #     source_platform: host_platform,
  #     target_platform: sub_tenant,
  #     mode: :auto_accept,
  #     policies: { content_sharing_policy: 'mirror_network_feed' }
  #   )
  #
  #   result.success?    # => true
  #   result.connection  # => BetterTogether::PlatformConnection instance
  #   result.mode        # => :request or :auto_accept
  class FederationConnectionProvisioningService
    VALID_MODES = %i[request auto_accept].freeze

    DEFAULT_POLICIES = {
      connection_kind: 'peer',
      content_sharing_enabled: false,
      federation_auth_enabled: false
    }.freeze

    Result = Struct.new(
      :connection,
      :mode,
      :errors
    ) do
      def success?
        errors.blank?
      end
    end

    def self.call(**)
      new(**).call
    end

    def initialize(source_platform:, target_platform:, policies: {}, mode: :request,
                   enqueue_sync: true)
      raise ArgumentError, "mode must be one of #{VALID_MODES.join(', ')}" unless VALID_MODES.include?(mode)

      @source_platform = source_platform
      @target_platform = target_platform
      @policies        = DEFAULT_POLICIES.merge(policies.symbolize_keys)
      @mode            = mode
      @enqueue_sync    = enqueue_sync
    end

    def call
      ActiveRecord::Base.transaction { build_result! }
    rescue ActiveRecord::RecordInvalid => e
      Result.new(connection: nil, mode: @mode, errors: e.record.errors.full_messages)
    rescue StandardError => e
      Result.new(connection: nil, mode: @mode, errors: [e.message])
    end

    private

    def build_result!
      connection = provision_connection!
      if @mode == :auto_accept && !connection.active?
        activate!(connection)
        enqueue_sync_job! if @enqueue_sync
      end
      Result.new(connection:, mode: @mode, errors: [])
    end

    def provision_connection!
      connection = ::BetterTogether::PlatformConnection.find_or_initialize_by(
        source_platform: @source_platform,
        target_platform: @target_platform
      )

      connection.assign_attributes(@policies)
      connection.save!
      connection
    end

    def activate!(connection)
      connection.update!(status: :active)
    end

    def enqueue_sync_job!
      ::BetterTogether::FederatedSyncScanJob.perform_later
    end
  end
end
