# frozen_string_literal: true

module BetterTogether
  # Provisions a federation connection between two platforms in a single transaction.
  #
  # Handles:
  #   - PlatformConnection creation (OAuth credentials auto-generated by model callback)
  #   - Connection policy configuration (content sharing + auth scopes)
  #   - Optional connection activation (status: active)
  #   - Optional sync job dispatch when activated
  #
  # Idempotent: uses find_or_initialize_by(source_platform:, target_platform:).
  # Calling with the same platform pair updates policies rather than duplicating.
  #
  # Usage:
  #   result = BetterTogether::FederationConnectionProvisioningService.call(
  #     source_platform: local_platform,
  #     target_platform: peer_platform,
  #     policies: {
  #       connection_kind: 'peer',
  #       content_sharing_policy: 'mirror_network_feed',
  #       federation_auth_policy: 'api_read',
  #       allow_content_read_scope: true
  #     },
  #     activate: true
  #   )
  #   result.success?    # => true
  #   result.connection  # => BetterTogether::PlatformConnection instance
  class FederationConnectionProvisioningService
    DEFAULT_POLICIES = {
      connection_kind: 'peer',
      content_sharing_enabled: false,
      federation_auth_enabled: false
    }.freeze

    Result = Struct.new(
      :connection,
      :errors,
      keyword_init: true
    ) do
      def success?
        errors.blank?
      end
    end

    def self.call(**)
      new(**).call
    end

    def initialize(source_platform:, target_platform:, policies: {}, activate: false,
                   enqueue_sync: true)
      @source_platform = source_platform
      @target_platform = target_platform
      @policies        = DEFAULT_POLICIES.merge(policies.symbolize_keys)
      @activate        = activate
      @enqueue_sync    = enqueue_sync
    end

    def call
      ActiveRecord::Base.transaction { build_result! }
    rescue ActiveRecord::RecordInvalid => e
      Result.new(connection: nil, errors: e.record.errors.full_messages)
    rescue StandardError => e
      Result.new(connection: nil, errors: [e.message])
    end

    private

    def build_result!
      connection = provision_connection!
      activate!(connection) if @activate && !connection.active?
      enqueue_sync_job! if @activate && @enqueue_sync
      Result.new(connection:, errors: [])
    end

    def provision_connection!
      connection = ::BetterTogether::PlatformConnection.find_or_initialize_by(
        source_platform: @source_platform,
        target_platform: @target_platform
      )

      connection.assign_attributes(@policies.except(:activate))
      connection.save!
      connection
    end

    def activate!(connection)
      connection.update!(status: :active)
    end

    def enqueue_sync_job!
      ::BetterTogether::FederatedSyncScanJob.perform_later
    end
  end
end
