name: i18n Translation Health Report

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  i18n-health:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Normalize locale files
        run: |
          bundle exec i18n-tasks normalize
      - name: Check missing translations
        run: |
          bundle exec i18n-tasks check-missing
      - name: Check consistent interpolations
        run: |
          bundle exec i18n-tasks check-consistent-interpolations
      - name: Upload i18n health report
        if: always()
        run: |
          bundle exec i18n-tasks health > i18n-health.txt
        continue-on-error: true
      - name: Archive i18n health report
        uses: actions/upload-artifact@v4
        with:
          name: i18n-health-report
          path: i18n-health.txt
    continue-on-error: true
